export { default as ResetPassword } from './ResetPassword/index';
export { default as Login } from './Login';
export { default as SetPassword } from './SetPassword';
export { default as AuthAction } from './AuthAction/AuthAction';
export { default as Register } from './Register/Register';
export { default as AppSumoRegister } from './AppSumoRegister/AppSumoRegister';
export { default as RegisterNew } from './RegisterNew/RegisterNew';
export { default as Dashboard } from './Dashboard/Dashboard';
// export { default as Integrations } from './Integrations/Integrations';
export { default as FraudBlockerTracker } from './Integrations/FraudBlockerTracker';
export { default as GoogleAdsSetup } from './Integrations/GoogleAdsSetup';
